const FAQS = [
  {
    q: "What are credits?",
    a: "Each generation (notes, chart, graph or PDF) costs credits. You start with 50 free credits when you sign up.",
  },
  {
    q: "What can I create?",
    a: "Exam notes, project notes, charts, graphs, downloadable PDFs and MCQ quizzes to test yourself — all generated by AI from your topic.",
  },
  {
    q: "Is it free?",
    a: "Yes, signing up is free and includes 50 credits. You can upgrade any time for more.",
  },
  {
    q: "Do I need an account?",
    a: "Just a Google account — sign in with one click, no passwords or forms.",
  },
];

function FAQ() {
  return (
    <section className="mx-3 sm:mx-6 md:mx-auto md:max-w-[85%] xl:max-w-[80%] mt-16 sm:mt-20 px-4">
      <h2 className="text-xl sm:text-2xl font-bold text-slate-900">
        Frequently asked questions
      </h2>
      <div className="mt-6 flex flex-col gap-3">
        {FAQS.map(({ q, a }) => (
          <details key={q} className="rounded-2xl border border-slate-200 bg-slate-50/90 p-4 transition-all">
            <summary className="cursor-pointer text-sm sm:text-base font-bold text-slate-900">
              {q}
            </summary>
            <p className="mt-2 text-sm text-slate-600 leading-relaxed">{a}</p>
          </details>
        ))}
      </div>
    </section>
  );
}

export default FAQ;
